apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: mysql
    app.kubernetes.io/owner: retail-store-sample
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "my-secret-pw"
  MYSQL_PASSWORD: "kalyandb101"