# Source: retail-store-sample-catalog-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "****"
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "****"
